# ML-07 — Baseline Action Score and Top-20 Review

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/abdulmoeed1090/Fly-rank-starter-assignment/blob/main/work/notebooks/w04_baseline_score.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My rule and its reason codes

### Baseline Rule

This baseline ranks content pages using a simple scoring rule based on search visibility and user engagement.

Pages with many impressions but relatively few clicks receive higher priority because they may have an opportunity for improvement. These pages are already visible in search results but may benefit from refreshed content, improved titles, or better metadata.

This rule is intentionally simple and transparent. It serves as the baseline that future machine learning models must outperform.

### Reason Codes

| Reason Code | Meaning | Recommended Action |
|--------------|---------|-------------------|
| HIGH_IMPRESSIONS_LOW_CLICKS | High visibility but relatively low clicks | Review and refresh the content |
| LOW_ENGAGEMENT | Users spend little time engaging with the page | Improve content quality |
| GOOD_PERFORMANCE | No immediate issue detected | Continue monitoring |

In [1]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

from google.colab import userdata
from huggingface_hub import login
from datasets import load_dataset
import pandas as pd

# Login to Hugging Face
hf_token = userdata.get("HF_TOKEN")
login(token=hf_token)

# Load the dataset
dataset = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_daily_performance"
)

print("Dataset loaded successfully!")
import pandas as pd

# Sample data
df = pd.DataFrame(dataset["train"][:50000])

# Simple baseline score
df["baseline_score"] = df["gsc_impressions"] - df["gsc_clicks"]

# Reason codes
df["reason_code"] = "GOOD_PERFORMANCE"

df.loc[
    (df["gsc_impressions"] > 100) &
    (df["gsc_clicks"] < 10),
    "reason_code"
] = "HIGH_IMPRESSIONS_LOW_CLICKS"

df.loc[
    df["ga4_total_engagement_sec"] < 30,
    "reason_code"
] = "LOW_ENGAGEMENT"

# Action labels
action_map = {
    "HIGH_IMPRESSIONS_LOW_CLICKS": "Refresh Content",
    "LOW_ENGAGEMENT": "Improve Content",
    "GOOD_PERFORMANCE": "Monitor"
}

df["action"] = df["reason_code"].map(action_map)

df.head()

README.md:   0%|          | 0.00/3.04k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 86.2MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 8.93MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 4.41MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 90.3MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 21.6MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  624kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 89.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.22MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 19.6kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  134MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 72.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 7.12MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 2.62MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 1.45MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  124MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.29MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  149MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  146MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/78835655 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/39 [00:00<?, ?it/s]

Dataset loaded successfully!

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events,baseline_score,reason_code,action
0,2025-01-27,client_9958f0a7ae1df715,content_3b70a18ea133b2bb,True,True,True,False,30,0,115.0,...,0,0,0,0,0,0,0,30,LOW_ENGAGEMENT,Improve Content
1,2025-01-27,client_9958f0a7ae1df715,content_fe8e8155ce1d47a2,True,True,True,False,5,0,358.0,...,0,0,0,0,0,0,0,5,LOW_ENGAGEMENT,Improve Content
2,2025-01-27,client_9958f0a7ae1df715,content_b4462a1b90640058,True,True,True,False,1,0,34.0,...,0,0,0,0,0,0,0,1,LOW_ENGAGEMENT,Improve Content
3,2025-01-27,client_9958f0a7ae1df715,content_c899aef92518c714,True,True,True,False,6,0,140.0,...,0,0,0,0,0,0,0,6,LOW_ENGAGEMENT,Improve Content
4,2025-01-27,client_9958f0a7ae1df715,content_c7c1d2e68d9d0964,True,True,True,False,5,0,89.0,...,0,0,0,0,0,0,0,5,LOW_ENGAGEMENT,Improve Content

## 2. Build the ranked queue (writes the CSV)

Each page receives a baseline score based on its search visibility.

Pages with higher scores are ranked first because they appear frequently in search results but receive comparatively fewer clicks.

The ranked queue helps prioritize which pages should be reviewed before building a machine learning model.

In [2]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

ranked_df = df.sort_values(
    by="baseline_score",
    ascending=False
)

ranked_df["rank"] = range(1, len(ranked_df)+1)

ranked_df[
    [
        "rank",
        "content_hash_id",
        "baseline_score",
        "reason_code",
        "action"
    ]
].head(20)

import os

os.makedirs("work/outputs", exist_ok=True)

ranked_df.to_csv(
    "work/outputs/baseline_action_score.csv",
    index=False
)

print("CSV saved successfully.")

CSV saved successfully.

## 3. Top-20 review

The top-ranked pages were manually reviewed based on the baseline score.

The confidence level is moderate because the ranking is produced by a simple rule rather than a trained machine learning model.

Some pages may receive high scores for reasons unrelated to content quality, so each recommendation should be reviewed by a human editor before any action is taken.

In [3]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

top20 = ranked_df.head(20)

review = top20[
    [
        "content_hash_id",
        "baseline_score",
        "reason_code",
        "action"
    ]
].copy()

review["confidence"] = "Medium"

review["what_would_make_it_wrong"] = (
    "High impressions may be caused by seasonal or temporary search trends."
)

review

,content_hash_id,baseline_score,reason_code,action,confidence,what_would_make_it_wrong
38579,content_690b092cf66bc2a4,805,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...
42839,content_690b092cf66bc2a4,726,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...
47089,content_690b092cf66bc2a4,701,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...
34266,content_690b092cf66bc2a4,582,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...
14715,content_a64143f6e4a21ffe,572,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...
12108,content_06de5368fbd3bf99,530,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...
12435,content_690b092cf66bc2a4,521,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...
21286,content_690b092cf66bc2a4,519,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...
41328,content_4d067c48a4f50221,503,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...
20971,content_06de5368fbd3bf99,499,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...
40553,content_a64143f6e4a21ffe,495,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...
6854,content_4e8d1e11f60fe6ba,495,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...
16908,content_690b092cf66bc2a4,482,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...
9596,content_4e8d1e11f60fe6ba,464,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...
19113,content_a64143f6e4a21ffe,446,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...
45316,content_e54599c7317c046d,446,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...
36349,content_a64143f6e4a21ffe,440,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...
33946,content_06de5368fbd3bf99,436,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...
12099,content_ce78d1eaabd3fc7a,436,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...
3825,content_213eb91f21a43550,424,LOW_ENGAGEMENT,Improve Content,Medium,High impressions may be caused by seasonal or ...

## 4. Weak picks + leakage check

The baseline is intentionally simple and may incorrectly rank some pages.

For example, a page may receive many impressions but naturally have a low click-through rate because of the search intent rather than poor content quality.

I confirmed that no future outcome variables, label-derived columns, or product-specific flags were used while constructing the baseline score. Only historical search and engagement metrics available before the prediction time were included.

In [4]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

print("Leakage Check")

used_features = [
    "gsc_impressions",
    "gsc_clicks",
    "ga4_total_engagement_sec"
]

excluded = [
    "client_hash_id",
    "content_hash_id",
    "report_date"
]

print("Used Features")
print(used_features)

print()

print("Excluded Fields")
print(excluded)

print()

print("No future information used.")

Leakage Check
Used Features
['gsc_impressions', 'gsc_clicks', 'ga4_total_engagement_sec']

Excluded Fields
['client_hash_id', 'content_hash_id', 'report_date']

No future information used.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.